// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function DownloadEz():Promise<void>;

export function DownloadInternal():Promise<void>;

export function DownloadSongBase():Promise<void>;

export function FillDatabase():Promise<void>;

export function GetCombinedPdf(arg1:Array<string>):Promise<string>;

export function GetCombinedPdfWithOptions(arg1:Array<string>,arg2:boolean,arg3:number):Promise<string>;

export function GetPdfFile(arg1:string):Promise<string>;

export function GetSongAuthors(arg1:number):Promise<Array<app.Author>>;

export function GetSongProjection(arg1:number):Promise<string>;

export function GetSongVerses(arg1:number):Promise<string>;

export function GetSongs(arg1:string,arg2:string):Promise<Array<app.dtoSong>>;

export function GetSongs2(arg1:string,arg2:string):Promise<Array<app.dtoSongHeader>>;

export function GetStatus():Promise<app.AppStatus>;

export function PrepareDatabase():Promise<void>;

export function ProcessKytaraPDF():Promise<void>;

export function ProjectionNextSong():Promise<void>;

export function ProjectionNextVerse():Promise<void>;

export function ProjectionPrevSong():Promise<void>;

export function ProjectionPrevVerse():Promise<void>;

export function ResetData():Promise<void>;

export function SaveSorting(arg1:app.SortingOption):Promise<void>;

export function Shutdown():Promise<void>;
