// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadEz() {
  return window['go']['app']['App']['DownloadEz']();
}

export function DownloadInternal() {
  return window['go']['app']['App']['DownloadInternal']();
}

export function DownloadKK() {
  return window['go']['app']['App']['DownloadKK']();
}

export function DownloadSongBase() {
  return window['go']['app']['App']['DownloadSongBase']();
}

export function FillDatabase() {
  return window['go']['app']['App']['FillDatabase']();
}

export function GetCombinedPdf(arg1) {
  return window['go']['app']['App']['GetCombinedPdf'](arg1);
}

export function GetCombinedPdfWithOptions(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetCombinedPdfWithOptions'](arg1, arg2, arg3);
}

export function GetPdfFile(arg1) {
  return window['go']['app']['App']['GetPdfFile'](arg1);
}

export function GetSongAuthors(arg1) {
  return window['go']['app']['App']['GetSongAuthors'](arg1);
}

export function GetSongProjection(arg1) {
  return window['go']['app']['App']['GetSongProjection'](arg1);
}

export function GetSongVerses(arg1) {
  return window['go']['app']['App']['GetSongVerses'](arg1);
}

export function GetSongs(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetSongs'](arg1, arg2, arg3);
}

export function GetSongs2(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetSongs2'](arg1, arg2, arg3);
}

export function GetStatus() {
  return window['go']['app']['App']['GetStatus']();
}

export function InitializeDatabase() {
  return window['go']['app']['App']['InitializeDatabase']();
}

export function ProcessKytaraPDF() {
  return window['go']['app']['App']['ProcessKytaraPDF']();
}

export function ProjectionNextSong() {
  return window['go']['app']['App']['ProjectionNextSong']();
}

export function ProjectionNextVerse() {
  return window['go']['app']['App']['ProjectionNextVerse']();
}

export function ProjectionPrevSong() {
  return window['go']['app']['App']['ProjectionPrevSong']();
}

export function ProjectionPrevVerse() {
  return window['go']['app']['App']['ProjectionPrevVerse']();
}

export function ResetData() {
  return window['go']['app']['App']['ResetData']();
}

export function SaveSorting(arg1) {
  return window['go']['app']['App']['SaveSorting'](arg1);
}

export function Shutdown() {
  return window['go']['app']['App']['Shutdown']();
}
