import '@testing-library/jest-dom';
import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import { vi } from 'vitest';

// Initialize i18n for tests
i18n
  .use(initReactI18next)
  .init({
    lng: 'cs',
    fallbackLng: 'cs',
    ns: ['translation'],
    defaultNS: 'translation',
    resources: {
      cs: {
        translation: {
          'infoBox.dataReady': 'Data jsou připravena',
          'infoBox.notInitialized': 'Zpěvník není inicializován',
          'infoBox.dataDownloadedNotImported': 'Data jsou stažena, ale nejsou naimportována do interní databáze',
          'infoBox.downloadData': 'Stáhnout data z internetu',
          'infoBox.importData': 'Importovat data',
          'infoBox.searchLabel': 'Hledat v textu',
          'infoBox.searchPlaceholder': 'Hledat text ...',
          'infoBox.sortLabel': 'Řadit podle',
          'infoBox.sortPlaceholder': 'Vyberte možnost',
          'infoBox.sortOptions.entry': 'čísla',
          'infoBox.sortOptions.title': 'názvu',
          'infoBox.sortOptions.authorMusic': 'autora hudby',
          'infoBox.sortOptions.authorLyric': 'autora textu',
          'infoBox.copyrightNotice': 'Upozorňujeme...',
          'songCard.showNotes': 'Zobrazit noty',
          'songCard.notesUnavailable': 'Noty nejsou dostupné',
          'songCard.authorWords': 'T:',
          'songCard.authorMusic': 'M:',
          'songCard.addToSelection': 'Přidat do výběru',
          'songCard.alreadyInSelection': 'Skladba už je ve výběru',
          'selectedSongs.title': 'Připravené písně',
          'selectedSongs.cancel': 'Zrušit',
          'selectedSongs.emptySelection': 'Výběr je prázdný',
          'selectedSongs.oneSong': '1 skladba ve výběru',
          'selectedSongs.multipleSongs': 'skladeb ve výběru: {{count}}',
          'selectedSongs.withoutNotes': '(bez not)',
          'selectedSongs.removeFromList': 'Odebrat ze seznamu',
          'selectedSongs.selectionLabel': 'Výběr skladeb',
          'selectedSongs.noNotesAvailable': 'Žádná z písní ve výběru nemá dostupné noty.',
          'selectedSongs.selectedHaveNoNotes': 'Vámi vybrané skladby nemají dostupné noty',
          'selectedSongs.showPreparedNotes': 'Zobrazit připravené noty',
          'selectedSongs.creatingPdf': 'Vytvářím PDF…',
          'selectedSongs.preparedNotes': 'Připravené noty',
          'selectedSongs.pdfCreationFailed': 'Nepodařilo se vytvořit společné PDF. Zkuste to prosím znovu.',
          'selectedSongs.projectText': 'Promítat texty',
          'selectedSongs.projectionWindowOpen': 'Projekční okno je již otevřeno.',
          'selectedSongs.projectionWindowFailed': 'Nelze otevřít projekční okno. Zkontrolujte blokování vyskakovacích oken.',
          'selectedSongs.projectionOpenFailed': 'Nepodařilo se otevřít projekční okno.',
          'selectedSongs.projectionControl': 'Řízení projekce:',
          'selectedSongs.closeProjector': '✕ Zavřít projektor',
          'selectedSongs.closeProjectorTitle': 'Zavřít projekční okno',
          'selectedSongs.prevVerse': '◀︎ Sloka',
          'selectedSongs.nextVerse': 'Sloka ▶︎',
          'selectedSongs.prevSong': '◀︎ Píseň',
          'selectedSongs.nextSong': 'Píseň ▶︎',
          'selectedSongs.prevVerseTitle': 'Předchozí verš',
          'selectedSongs.nextVerseTitle': 'Další verš',
          'selectedSongs.prevSongTitle': 'Předchozí píseň',
          'selectedSongs.nextSongTitle': 'Další píseň',
          'selectedSongs.selectScreen': 'Vyberte displej pro projekci:',
          'selectedSongs.primary': '(Primární)',
          'pdfModal.close': 'Zavřít (Esc)',
          'pdfModal.loadingPdf': 'Načítání PDF...',
        },
      },
      en: {
        translation: {
          'infoBox.dataReady': 'Data is ready',
          'infoBox.notInitialized': 'Songbook is not initialized',
          'infoBox.dataDownloadedNotImported': 'Data is downloaded but not imported to internal database',
          'infoBox.downloadData': 'Download data from internet',
          'infoBox.importData': 'Import data',
          'infoBox.searchLabel': 'Search in text',
          'infoBox.searchPlaceholder': 'Search for text ...',
          'infoBox.sortLabel': 'Sort by',
          'infoBox.sortPlaceholder': 'Select an option',
          'infoBox.sortOptions.entry': 'entry number',
          'infoBox.sortOptions.title': 'title',
          'infoBox.sortOptions.authorMusic': 'music author',
          'infoBox.sortOptions.authorLyric': 'lyric author',
          'infoBox.copyrightNotice': 'Please note...',
          'songCard.showNotes': 'Show notes',
          'songCard.notesUnavailable': 'Notes are not available',
          'songCard.authorWords': 'L:',
          'songCard.authorMusic': 'M:',
          'songCard.addToSelection': 'Add to selection',
          'songCard.alreadyInSelection': 'Song is already in selection',
          'selectedSongs.title': 'Selected songs',
          'selectedSongs.cancel': 'Cancel',
          'selectedSongs.emptySelection': 'Selection is empty',
          'selectedSongs.oneSong': '1 song in selection',
          'selectedSongs.multipleSongs': 'songs in selection: {{count}}',
          'selectedSongs.withoutNotes': '(without notes)',
          'selectedSongs.removeFromList': 'Remove from list',
          'selectedSongs.selectionLabel': 'Song selection',
          'selectedSongs.noNotesAvailable': 'None of the songs in selection have available notes.',
          'selectedSongs.selectedHaveNoNotes': 'Your selected songs do not have available notes',
          'selectedSongs.showPreparedNotes': 'Show prepared notes',
          'selectedSongs.creatingPdf': 'Creating PDF…',
          'selectedSongs.preparedNotes': 'Prepared notes',
          'selectedSongs.pdfCreationFailed': 'Failed to create combined PDF. Please try again.',
          'selectedSongs.projectText': 'Project lyrics',
          'selectedSongs.projectionWindowOpen': 'Projection window is already open.',
          'selectedSongs.projectionWindowFailed': 'Unable to open projection window. Check popup blocker settings.',
          'selectedSongs.projectionOpenFailed': 'Failed to open projection window.',
          'selectedSongs.projectionControl': 'Projection control:',
          'selectedSongs.closeProjector': '✕ Close projector',
          'selectedSongs.closeProjectorTitle': 'Close projection window',
          'selectedSongs.prevVerse': '◀︎ Verse',
          'selectedSongs.nextVerse': 'Verse ▶︎',
          'selectedSongs.prevSong': '◀︎ Song',
          'selectedSongs.nextSong': 'Song ▶︎',
          'selectedSongs.prevVerseTitle': 'Previous verse',
          'selectedSongs.nextVerseTitle': 'Next verse',
          'selectedSongs.prevSongTitle': 'Previous song',
          'selectedSongs.nextSongTitle': 'Next song',
          'selectedSongs.selectScreen': 'Select display for projection:',
          'selectedSongs.primary': '(Primary)',
          'pdfModal.close': 'Close (Esc)',
          'pdfModal.loadingPdf': 'Loading PDF...',
        },
      },
    },
    interpolation: {
      escapeValue: false,
    },
  });

// Mock Wails runtime
vi.mock('../../wailsjs/go/app/App', () => ({
  GetSongs2: vi.fn(),
  GetSongAuthors: vi.fn(),
  DownloadSongBase: vi.fn(),
  GetFilteredSongs: vi.fn(),
}))
