// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadEz() {
  return window['go']['main']['App']['DownloadEz']();
}

export function DownloadInternal() {
  return window['go']['main']['App']['DownloadInternal']();
}

export function DownloadSongBase() {
  return window['go']['main']['App']['DownloadSongBase']();
}

export function FillDatabase() {
  return window['go']['main']['App']['FillDatabase']();
}

export function GetSongs() {
  return window['go']['main']['App']['GetSongs']();
}

export function PrepareDatabase() {
  return window['go']['main']['App']['PrepareDatabase']();
}
