// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadEz() {
  return window['go']['main']['App']['DownloadEz']();
}

export function DownloadInternal() {
  return window['go']['main']['App']['DownloadInternal']();
}

export function DownloadSongBase() {
  return window['go']['main']['App']['DownloadSongBase']();
}
