// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadEz():Promise<void>;

export function DownloadInternal():Promise<void>;

export function DownloadSongBase():Promise<void>;
