// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DownloadEz():Promise<void>;

export function DownloadInternal():Promise<void>;

export function DownloadSongBase():Promise<void>;

export function FillDatabase():Promise<void>;

export function GetSongAuthors(arg1:number):Promise<Array<main.Author>>;

export function GetSongs(arg1:string,arg2:string):Promise<Array<main.dtoSong>>;

export function GetSongs2(arg1:string,arg2:string):Promise<Array<main.dtoSongHeader>>;

export function GetStatus():Promise<main.AppStatus>;

export function PrepareDatabase():Promise<void>;

export function SaveSorting(arg1:main.SortingOption):Promise<void>;
