// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadEz() {
  return window['go']['main']['App']['DownloadEz']();
}

export function DownloadInternal() {
  return window['go']['main']['App']['DownloadInternal']();
}

export function DownloadSongBase() {
  return window['go']['main']['App']['DownloadSongBase']();
}

export function FillDatabase() {
  return window['go']['main']['App']['FillDatabase']();
}

export function GetPdfFile(arg1) {
  return window['go']['main']['App']['GetPdfFile'](arg1);
}

export function GetSongAuthors(arg1) {
  return window['go']['main']['App']['GetSongAuthors'](arg1);
}

export function GetSongs(arg1, arg2) {
  return window['go']['main']['App']['GetSongs'](arg1, arg2);
}

export function GetSongs2(arg1, arg2) {
  return window['go']['main']['App']['GetSongs2'](arg1, arg2);
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function PrepareDatabase() {
  return window['go']['main']['App']['PrepareDatabase']();
}

export function ProcessKytaraPDF() {
  return window['go']['main']['App']['ProcessKytaraPDF']();
}

export function SaveSorting(arg1) {
  return window['go']['main']['App']['SaveSorting'](arg1);
}
