// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DownloadEz():Promise<void>;

export function DownloadInternal():Promise<void>;

export function DownloadSongBase():Promise<void>;

export function FillDatabase():Promise<void>;

export function GetSongs():Promise<Array<main.dtoSong>>;

export function PrepareDatabase():Promise<void>;
